import categoryList from "@/content/block-categories.json";
import meta from "./blocks-meta.json";

export interface BlockCategory {
  slug: string;
  title: string;
  /** H1 on the category page — phrased the way people search */
  heading: string;
  description: string;
}

export interface BlockMeta {
  slug: string;
  title: string;
  description: string;
  category: string;
  order?: number;
  exportName: string;
  /** Velora components the block imports (installed by the CLI) */
  components: string[];
  /** shadcn/ui primitives the block imports */
  ui: string[];
  /** npm packages the block imports directly */
  dependencies: string[];
}

/** Generated by scripts/build-docs.mjs from src/content/blocks/<slug>/. */
export const blocksMeta = meta as BlockMeta[];

export const blockCategories = categoryList as BlockCategory[];

export const blocksIn = (category: string) =>
  blocksMeta.filter((b) => b.category === category);
