import categoryList from "@/content/categories.json";
import categoryCopy from "@/content/component-category-copy.json";
import meta from "./components-meta.json";

export interface ComponentExampleMeta {
  name: string;
  title: string;
  description?: string;
}

export interface ComponentA11y {
  /** What a prefers-reduced-motion user sees */
  motion: string;
  /** Keyboard behavior; null for decorative, non-interactive components */
  keyboard: string | null;
  /** What assistive tech announces */
  screenReader: string;
}

export interface ComponentMeta {
  slug: string;
  title: string;
  description: string;
  category: string;
  dependencies: string[];
  examples: ComponentExampleMeta[];
  a11y?: ComponentA11y;
}

/**
 * Generated by scripts/build-docs.mjs from src/content/components/<slug>/.
 * Single source of truth for the docs site and the shadcn registry
 * (scripts/build-registry.mjs reads the same JSON).
 */
export const componentsMeta = meta as ComponentMeta[];

export const categories = categoryList as readonly string[];

/** "Cards & Layout" → "cards-layout" */
export const categorySlug = (category: string) =>
  category.toLowerCase().replace(/&/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const categoryFromSlug = (slug: string) =>
  categories.find((c) => categorySlug(c) === slug);

/** Search-phrased heading and intro for each category hub page */
export const categoryInfo = categoryCopy as Record<
  string,
  { heading: string; description: string }
>;
