import categoryList from "@/content/categories.json";
import meta from "./components-meta.json";

export interface ComponentExampleMeta {
  name: string;
  title: string;
  description?: string;
}

export interface ComponentA11y {
  /** What a prefers-reduced-motion user sees */
  motion: string;
  /** Keyboard behavior; null for decorative, non-interactive components */
  keyboard: string | null;
  /** What assistive tech announces */
  screenReader: string;
}

export interface ComponentMeta {
  slug: string;
  title: string;
  description: string;
  category: string;
  dependencies: string[];
  examples: ComponentExampleMeta[];
  a11y?: ComponentA11y;
}

/**
 * Generated by scripts/build-docs.mjs from src/content/components/<slug>/.
 * Single source of truth for the docs site and the shadcn registry
 * (scripts/build-registry.mjs reads the same JSON).
 */
export const componentsMeta = meta as ComponentMeta[];

export const categories = categoryList as readonly string[];
