// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

import ExampleAuroraBackgroundDefault from "./aurora-background/examples/default";
import ExampleBackgroundBeamsDefault from "./background-beams/examples/default";
import ExampleBackgroundBoxesDefault from "./background-boxes/examples/default";
import ExampleBackgroundBoxesHeadline from "./background-boxes/examples/headline";
import ExampleDottedGlowBackgroundDefault from "./dotted-glow-background/examples/default";
import ExampleDottedGlowBackgroundPricingCard from "./dotted-glow-background/examples/pricing-card";
import ExampleFlickeringGridDefault from "./flickering-grid/examples/default";
import ExampleGridPatternDefault from "./grid-pattern/examples/default";
import ExampleLampDefault from "./lamp/examples/default";
import ExampleLightRaysDefault from "./light-rays/examples/default";
import ExampleMeteorsDefault from "./meteors/examples/default";
import ExampleNoiseBackgroundDefault from "./noise-background/examples/default";
import ExampleNoiseBackgroundNewsletter from "./noise-background/examples/newsletter";
import ExampleParticlesDefault from "./particles/examples/default";
import ExampleRetroGridDefault from "./retro-grid/examples/default";
import ExampleRippleDefault from "./ripple/examples/default";
import ExampleShootingStarsDefault from "./shooting-stars/examples/default";
import ExampleShootingStarsNightSky from "./shooting-stars/examples/night-sky";
import ExampleVortexDefault from "./vortex/examples/default";
import ExampleVortexCtaBand from "./vortex/examples/cta-band";
import ExampleWavyBackgroundDefault from "./wavy-background/examples/default";
import ExampleWavyBackgroundHero from "./wavy-background/examples/hero";
import ExampleAnimatedGradientTextDefault from "./animated-gradient-text/examples/default";
import ExampleFlipWordsDefault from "./flip-words/examples/default";
import ExampleHyperTextDefault from "./hyper-text/examples/default";
import ExampleMorphingTextDefault from "./morphing-text/examples/default";
import ExampleNumberTickerDefault from "./number-ticker/examples/default";
import ExampleSparklesTextDefault from "./sparkles-text/examples/default";
import ExampleTextHighlighterDefault from "./text-highlighter/examples/default";
import ExampleTextHoverEffectDefault from "./text-hover-effect/examples/default";
import ExampleTextHoverEffectFooterWordmark from "./text-hover-effect/examples/footer-wordmark";
import ExampleTextRevealDefault from "./text-reveal/examples/default";
import ExampleTextShimmerDefault from "./text-shimmer/examples/default";
import ExampleTypewriterDefault from "./typewriter/examples/default";
import ExampleWordRotateDefault from "./word-rotate/examples/default";
import ExampleConfettiDefault from "./confetti/examples/default";
import ExampleMagneticButtonDefault from "./magnetic-button/examples/default";
import ExampleMovingBorderDefault from "./moving-border/examples/default";
import ExampleRainbowButtonDefault from "./rainbow-button/examples/default";
import ExampleRippleButtonDefault from "./ripple-button/examples/default";
import ExampleShimmerButtonDefault from "./shimmer-button/examples/default";
import ExampleStatefulButtonDefault from "./stateful-button/examples/default";
import ExampleStatefulButtonForm from "./stateful-button/examples/form";
import ExampleThemeTogglerDefault from "./theme-toggler/examples/default";
import ExampleAnimatedListDefault from "./animated-list/examples/default";
import ExampleAnimatedTooltipDefault from "./animated-tooltip/examples/default";
import ExampleAvatarCirclesDefault from "./avatar-circles/examples/default";
import ExampleBentoGridDefault from "./bento-grid/examples/default";
import ExampleCardHoverEffectDefault from "./card-hover-effect/examples/default";
import ExampleCardHoverEffectIntegrations from "./card-hover-effect/examples/integrations";
import ExampleCardStackDefault from "./card-stack/examples/default";
import ExampleCompareSliderDefault from "./compare-slider/examples/default";
import ExampleDirectionAwareHoverDefault from "./direction-aware-hover/examples/default";
import ExampleDockDefault from "./dock/examples/default";
import ExampleDraggableCardDefault from "./draggable-card/examples/default";
import ExampleDraggableCardMoodboard from "./draggable-card/examples/moodboard";
import ExampleEvervaultCardDefault from "./evervault-card/examples/default";
import ExampleEvervaultCardEncryptedAtRest from "./evervault-card/examples/encrypted-at-rest";
import ExampleExpandableCardDefault from "./expandable-card/examples/default";
import ExampleFileTreeDefault from "./file-tree/examples/default";
import ExampleFocusCardsDefault from "./focus-cards/examples/default";
import ExampleFocusCardsDestinations from "./focus-cards/examples/destinations";
import ExampleGlareCardDefault from "./glare-card/examples/default";
import ExampleLayoutGridDefault from "./layout-grid/examples/default";
import ExampleLayoutGridTravelStories from "./layout-grid/examples/travel-stories";
import ExampleMarqueeDefault from "./marquee/examples/default";
import ExampleOrbitingCirclesDefault from "./orbiting-circles/examples/default";
import ExampleSpotlightCardDefault from "./spotlight-card/examples/default";
import ExampleTiltCardDefault from "./tilt-card/examples/default";
import ExampleWobbleCardDefault from "./wobble-card/examples/default";
import ExampleWobbleCardFeatureBento from "./wobble-card/examples/feature-bento";
import ExampleAnimatedSidebarDefault from "./animated-sidebar/examples/default";
import ExampleAnimatedSidebarDashboard from "./animated-sidebar/examples/dashboard";
import ExampleAnimatedSidebarNarrow from "./animated-sidebar/examples/narrow";
import ExampleAnimatedTabsDefault from "./animated-tabs/examples/default";
import ExampleAnimatedTabsFeatureTour from "./animated-tabs/examples/feature-tour";
import ExampleFloatingNavbarDefault from "./floating-navbar/examples/default";
import ExampleNavbarMenuDefault from "./navbar-menu/examples/default";
import ExampleResizableNavbarDefault from "./resizable-navbar/examples/default";
import ExampleResizableNavbarLandingPage from "./resizable-navbar/examples/landing-page";
import ExampleStickyBannerDefault from "./sticky-banner/examples/default";
import ExampleFileDropDefault from "./file-drop/examples/default";
import ExampleStepperDefault from "./stepper/examples/default";
import ExampleVanishInputDefault from "./vanish-input/examples/default";
import ExampleAnimatedModalDefault from "./animated-modal/examples/default";
import ExampleAnimatedModalBookTrip from "./animated-modal/examples/book-trip";
import ExampleLoadersDefault from "./loaders/examples/default";
import ExampleLoadersInContext from "./loaders/examples/in-context";
import ExampleMultiStepLoaderDefault from "./multi-step-loader/examples/default";
import ExampleMultiStepLoaderDeploy from "./multi-step-loader/examples/deploy";
import ExampleAnimatedTestimonialsDefault from "./animated-testimonials/examples/default";
import ExampleLogoCloudDefault from "./logo-cloud/examples/default";
import ExampleTweetCardDefault from "./tweet-card/examples/default";
import ExampleContainerScrollDefault from "./container-scroll/examples/default";
import ExampleHeroParallaxDefault from "./hero-parallax/examples/default";
import ExampleHeroParallaxAgency from "./hero-parallax/examples/agency";
import ExampleMacbookScrollDefault from "./macbook-scroll/examples/default";
import ExampleMacbookScrollDashboard from "./macbook-scroll/examples/dashboard";
import ExampleParallaxGridDefault from "./parallax-grid/examples/default";
import ExampleScrollProgressDefault from "./scroll-progress/examples/default";
import ExampleScrollVelocityDefault from "./scroll-velocity/examples/default";
import ExampleStickyScrollDefault from "./sticky-scroll/examples/default";
import ExampleTimelineDefault from "./timeline/examples/default";
import ExampleTimelineChangelog from "./timeline/examples/changelog";
import ExampleTracingBeamDefault from "./tracing-beam/examples/default";
import ExampleAnimatedBeamDefault from "./animated-beam/examples/default";
import ExampleBlurFadeDefault from "./blur-fade/examples/default";
import ExampleBorderBeamDefault from "./border-beam/examples/default";
import ExampleGlowingEffectDefault from "./glowing-effect/examples/default";
import ExampleGlowingEffectFeatureGrid from "./glowing-effect/examples/feature-grid";
import Example3dCardDefault from "./3d-card/examples/default";
import Example3dCardProductCard from "./3d-card/examples/product-card";
import Example3dPinDefault from "./3d-pin/examples/default";
import Example3dPinProjectShowcase from "./3d-pin/examples/project-showcase";
import Example3dMarqueeDefault from "./3d-marquee/examples/default";
import Example3dMarqueeShowcaseWall from "./3d-marquee/examples/showcase-wall";
import ExampleAppleCardsCarouselDefault from "./apple-cards-carousel/examples/default";
import ExampleAppleCardsCarouselFeatures from "./apple-cards-carousel/examples/features";
import ExampleImageSliderDefault from "./image-slider/examples/default";
import ExampleImageSliderHero from "./image-slider/examples/hero";
import ExampleFollowingPointerDefault from "./following-pointer/examples/default";
import ExampleFollowingPointerBlogGrid from "./following-pointer/examples/blog-grid";
import ExampleLensDefault from "./lens/examples/default";
import ExampleLensProductInspector from "./lens/examples/product-inspector";
import ExamplePointerHighlightDefault from "./pointer-highlight/examples/default";
import ExamplePointerHighlightHero from "./pointer-highlight/examples/hero";
import ExampleSmoothCursorDefault from "./smooth-cursor/examples/default";
import ExampleSmoothCursorCtaCard from "./smooth-cursor/examples/cta-card";
import ExampleGlobeDefault from "./globe/examples/default";
import ExampleGlobeEdgeNetwork from "./globe/examples/edge-network";
import ExampleWorldMapDefault from "./world-map/examples/default";
import ExampleWorldMapRemoteTeam from "./world-map/examples/remote-team";
import ExampleBrowserMockupDefault from "./browser-mockup/examples/default";
import ExampleCodeBlockDefault from "./code-block/examples/default";
import ExampleCodeBlockTabs from "./code-block/examples/tabs";
import ExampleIphoneMockupDefault from "./iphone-mockup/examples/default";
import ExampleTerminalDefault from "./terminal/examples/default";

export const componentExamples: Record<
  string,
  { name: string; Component: ComponentType }[]
> = {
  "aurora-background": [{ name: "default", Component: ExampleAuroraBackgroundDefault }],
  "background-beams": [{ name: "default", Component: ExampleBackgroundBeamsDefault }],
  "background-boxes": [{ name: "default", Component: ExampleBackgroundBoxesDefault }, { name: "headline", Component: ExampleBackgroundBoxesHeadline }],
  "dotted-glow-background": [{ name: "default", Component: ExampleDottedGlowBackgroundDefault }, { name: "pricing-card", Component: ExampleDottedGlowBackgroundPricingCard }],
  "flickering-grid": [{ name: "default", Component: ExampleFlickeringGridDefault }],
  "grid-pattern": [{ name: "default", Component: ExampleGridPatternDefault }],
  "lamp": [{ name: "default", Component: ExampleLampDefault }],
  "light-rays": [{ name: "default", Component: ExampleLightRaysDefault }],
  "meteors": [{ name: "default", Component: ExampleMeteorsDefault }],
  "noise-background": [{ name: "default", Component: ExampleNoiseBackgroundDefault }, { name: "newsletter", Component: ExampleNoiseBackgroundNewsletter }],
  "particles": [{ name: "default", Component: ExampleParticlesDefault }],
  "retro-grid": [{ name: "default", Component: ExampleRetroGridDefault }],
  "ripple": [{ name: "default", Component: ExampleRippleDefault }],
  "shooting-stars": [{ name: "default", Component: ExampleShootingStarsDefault }, { name: "night-sky", Component: ExampleShootingStarsNightSky }],
  "vortex": [{ name: "default", Component: ExampleVortexDefault }, { name: "cta-band", Component: ExampleVortexCtaBand }],
  "wavy-background": [{ name: "default", Component: ExampleWavyBackgroundDefault }, { name: "hero", Component: ExampleWavyBackgroundHero }],
  "animated-gradient-text": [{ name: "default", Component: ExampleAnimatedGradientTextDefault }],
  "flip-words": [{ name: "default", Component: ExampleFlipWordsDefault }],
  "hyper-text": [{ name: "default", Component: ExampleHyperTextDefault }],
  "morphing-text": [{ name: "default", Component: ExampleMorphingTextDefault }],
  "number-ticker": [{ name: "default", Component: ExampleNumberTickerDefault }],
  "sparkles-text": [{ name: "default", Component: ExampleSparklesTextDefault }],
  "text-highlighter": [{ name: "default", Component: ExampleTextHighlighterDefault }],
  "text-hover-effect": [{ name: "default", Component: ExampleTextHoverEffectDefault }, { name: "footer-wordmark", Component: ExampleTextHoverEffectFooterWordmark }],
  "text-reveal": [{ name: "default", Component: ExampleTextRevealDefault }],
  "text-shimmer": [{ name: "default", Component: ExampleTextShimmerDefault }],
  "typewriter": [{ name: "default", Component: ExampleTypewriterDefault }],
  "word-rotate": [{ name: "default", Component: ExampleWordRotateDefault }],
  "confetti": [{ name: "default", Component: ExampleConfettiDefault }],
  "magnetic-button": [{ name: "default", Component: ExampleMagneticButtonDefault }],
  "moving-border": [{ name: "default", Component: ExampleMovingBorderDefault }],
  "rainbow-button": [{ name: "default", Component: ExampleRainbowButtonDefault }],
  "ripple-button": [{ name: "default", Component: ExampleRippleButtonDefault }],
  "shimmer-button": [{ name: "default", Component: ExampleShimmerButtonDefault }],
  "stateful-button": [{ name: "default", Component: ExampleStatefulButtonDefault }, { name: "form", Component: ExampleStatefulButtonForm }],
  "theme-toggler": [{ name: "default", Component: ExampleThemeTogglerDefault }],
  "animated-list": [{ name: "default", Component: ExampleAnimatedListDefault }],
  "animated-tooltip": [{ name: "default", Component: ExampleAnimatedTooltipDefault }],
  "avatar-circles": [{ name: "default", Component: ExampleAvatarCirclesDefault }],
  "bento-grid": [{ name: "default", Component: ExampleBentoGridDefault }],
  "card-hover-effect": [{ name: "default", Component: ExampleCardHoverEffectDefault }, { name: "integrations", Component: ExampleCardHoverEffectIntegrations }],
  "card-stack": [{ name: "default", Component: ExampleCardStackDefault }],
  "compare-slider": [{ name: "default", Component: ExampleCompareSliderDefault }],
  "direction-aware-hover": [{ name: "default", Component: ExampleDirectionAwareHoverDefault }],
  "dock": [{ name: "default", Component: ExampleDockDefault }],
  "draggable-card": [{ name: "default", Component: ExampleDraggableCardDefault }, { name: "moodboard", Component: ExampleDraggableCardMoodboard }],
  "evervault-card": [{ name: "default", Component: ExampleEvervaultCardDefault }, { name: "encrypted-at-rest", Component: ExampleEvervaultCardEncryptedAtRest }],
  "expandable-card": [{ name: "default", Component: ExampleExpandableCardDefault }],
  "file-tree": [{ name: "default", Component: ExampleFileTreeDefault }],
  "focus-cards": [{ name: "default", Component: ExampleFocusCardsDefault }, { name: "destinations", Component: ExampleFocusCardsDestinations }],
  "glare-card": [{ name: "default", Component: ExampleGlareCardDefault }],
  "layout-grid": [{ name: "default", Component: ExampleLayoutGridDefault }, { name: "travel-stories", Component: ExampleLayoutGridTravelStories }],
  "marquee": [{ name: "default", Component: ExampleMarqueeDefault }],
  "orbiting-circles": [{ name: "default", Component: ExampleOrbitingCirclesDefault }],
  "spotlight-card": [{ name: "default", Component: ExampleSpotlightCardDefault }],
  "tilt-card": [{ name: "default", Component: ExampleTiltCardDefault }],
  "wobble-card": [{ name: "default", Component: ExampleWobbleCardDefault }, { name: "feature-bento", Component: ExampleWobbleCardFeatureBento }],
  "animated-sidebar": [{ name: "default", Component: ExampleAnimatedSidebarDefault }, { name: "dashboard", Component: ExampleAnimatedSidebarDashboard }, { name: "narrow", Component: ExampleAnimatedSidebarNarrow }],
  "animated-tabs": [{ name: "default", Component: ExampleAnimatedTabsDefault }, { name: "feature-tour", Component: ExampleAnimatedTabsFeatureTour }],
  "floating-navbar": [{ name: "default", Component: ExampleFloatingNavbarDefault }],
  "navbar-menu": [{ name: "default", Component: ExampleNavbarMenuDefault }],
  "resizable-navbar": [{ name: "default", Component: ExampleResizableNavbarDefault }, { name: "landing-page", Component: ExampleResizableNavbarLandingPage }],
  "sticky-banner": [{ name: "default", Component: ExampleStickyBannerDefault }],
  "file-drop": [{ name: "default", Component: ExampleFileDropDefault }],
  "stepper": [{ name: "default", Component: ExampleStepperDefault }],
  "vanish-input": [{ name: "default", Component: ExampleVanishInputDefault }],
  "animated-modal": [{ name: "default", Component: ExampleAnimatedModalDefault }, { name: "book-trip", Component: ExampleAnimatedModalBookTrip }],
  "loaders": [{ name: "default", Component: ExampleLoadersDefault }, { name: "in-context", Component: ExampleLoadersInContext }],
  "multi-step-loader": [{ name: "default", Component: ExampleMultiStepLoaderDefault }, { name: "deploy", Component: ExampleMultiStepLoaderDeploy }],
  "animated-testimonials": [{ name: "default", Component: ExampleAnimatedTestimonialsDefault }],
  "logo-cloud": [{ name: "default", Component: ExampleLogoCloudDefault }],
  "tweet-card": [{ name: "default", Component: ExampleTweetCardDefault }],
  "container-scroll": [{ name: "default", Component: ExampleContainerScrollDefault }],
  "hero-parallax": [{ name: "default", Component: ExampleHeroParallaxDefault }, { name: "agency", Component: ExampleHeroParallaxAgency }],
  "macbook-scroll": [{ name: "default", Component: ExampleMacbookScrollDefault }, { name: "dashboard", Component: ExampleMacbookScrollDashboard }],
  "parallax-grid": [{ name: "default", Component: ExampleParallaxGridDefault }],
  "scroll-progress": [{ name: "default", Component: ExampleScrollProgressDefault }],
  "scroll-velocity": [{ name: "default", Component: ExampleScrollVelocityDefault }],
  "sticky-scroll": [{ name: "default", Component: ExampleStickyScrollDefault }],
  "timeline": [{ name: "default", Component: ExampleTimelineDefault }, { name: "changelog", Component: ExampleTimelineChangelog }],
  "tracing-beam": [{ name: "default", Component: ExampleTracingBeamDefault }],
  "animated-beam": [{ name: "default", Component: ExampleAnimatedBeamDefault }],
  "blur-fade": [{ name: "default", Component: ExampleBlurFadeDefault }],
  "border-beam": [{ name: "default", Component: ExampleBorderBeamDefault }],
  "glowing-effect": [{ name: "default", Component: ExampleGlowingEffectDefault }, { name: "feature-grid", Component: ExampleGlowingEffectFeatureGrid }],
  "3d-card": [{ name: "default", Component: Example3dCardDefault }, { name: "product-card", Component: Example3dCardProductCard }],
  "3d-pin": [{ name: "default", Component: Example3dPinDefault }, { name: "project-showcase", Component: Example3dPinProjectShowcase }],
  "3d-marquee": [{ name: "default", Component: Example3dMarqueeDefault }, { name: "showcase-wall", Component: Example3dMarqueeShowcaseWall }],
  "apple-cards-carousel": [{ name: "default", Component: ExampleAppleCardsCarouselDefault }, { name: "features", Component: ExampleAppleCardsCarouselFeatures }],
  "image-slider": [{ name: "default", Component: ExampleImageSliderDefault }, { name: "hero", Component: ExampleImageSliderHero }],
  "following-pointer": [{ name: "default", Component: ExampleFollowingPointerDefault }, { name: "blog-grid", Component: ExampleFollowingPointerBlogGrid }],
  "lens": [{ name: "default", Component: ExampleLensDefault }, { name: "product-inspector", Component: ExampleLensProductInspector }],
  "pointer-highlight": [{ name: "default", Component: ExamplePointerHighlightDefault }, { name: "hero", Component: ExamplePointerHighlightHero }],
  "smooth-cursor": [{ name: "default", Component: ExampleSmoothCursorDefault }, { name: "cta-card", Component: ExampleSmoothCursorCtaCard }],
  "globe": [{ name: "default", Component: ExampleGlobeDefault }, { name: "edge-network", Component: ExampleGlobeEdgeNetwork }],
  "world-map": [{ name: "default", Component: ExampleWorldMapDefault }, { name: "remote-team", Component: ExampleWorldMapRemoteTeam }],
  "browser-mockup": [{ name: "default", Component: ExampleBrowserMockupDefault }],
  "code-block": [{ name: "default", Component: ExampleCodeBlockDefault }, { name: "tabs", Component: ExampleCodeBlockTabs }],
  "iphone-mockup": [{ name: "default", Component: ExampleIphoneMockupDefault }],
  "terminal": [{ name: "default", Component: ExampleTerminalDefault }],
};
