// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

import AuroraBackgroundDefault from "./aurora-background/examples/default";
import BackgroundBeamsDefault from "./background-beams/examples/default";
import FlickeringGridDefault from "./flickering-grid/examples/default";
import GridPatternDefault from "./grid-pattern/examples/default";
import LampDefault from "./lamp/examples/default";
import LightRaysDefault from "./light-rays/examples/default";
import MeteorsDefault from "./meteors/examples/default";
import ParticlesDefault from "./particles/examples/default";
import RetroGridDefault from "./retro-grid/examples/default";
import RippleDefault from "./ripple/examples/default";
import AnimatedGradientTextDefault from "./animated-gradient-text/examples/default";
import FlipWordsDefault from "./flip-words/examples/default";
import HyperTextDefault from "./hyper-text/examples/default";
import MorphingTextDefault from "./morphing-text/examples/default";
import NumberTickerDefault from "./number-ticker/examples/default";
import SparklesTextDefault from "./sparkles-text/examples/default";
import TextHighlighterDefault from "./text-highlighter/examples/default";
import TextRevealDefault from "./text-reveal/examples/default";
import TextShimmerDefault from "./text-shimmer/examples/default";
import TypewriterDefault from "./typewriter/examples/default";
import WordRotateDefault from "./word-rotate/examples/default";
import ConfettiDefault from "./confetti/examples/default";
import MagneticButtonDefault from "./magnetic-button/examples/default";
import MovingBorderDefault from "./moving-border/examples/default";
import RainbowButtonDefault from "./rainbow-button/examples/default";
import RippleButtonDefault from "./ripple-button/examples/default";
import ShimmerButtonDefault from "./shimmer-button/examples/default";
import ThemeTogglerDefault from "./theme-toggler/examples/default";
import AnimatedListDefault from "./animated-list/examples/default";
import AnimatedTooltipDefault from "./animated-tooltip/examples/default";
import AvatarCirclesDefault from "./avatar-circles/examples/default";
import BentoGridDefault from "./bento-grid/examples/default";
import CardStackDefault from "./card-stack/examples/default";
import CompareSliderDefault from "./compare-slider/examples/default";
import DirectionAwareHoverDefault from "./direction-aware-hover/examples/default";
import DockDefault from "./dock/examples/default";
import ExpandableCardDefault from "./expandable-card/examples/default";
import FileTreeDefault from "./file-tree/examples/default";
import GlareCardDefault from "./glare-card/examples/default";
import MarqueeDefault from "./marquee/examples/default";
import OrbitingCirclesDefault from "./orbiting-circles/examples/default";
import SpotlightCardDefault from "./spotlight-card/examples/default";
import TiltCardDefault from "./tilt-card/examples/default";
import FloatingNavbarDefault from "./floating-navbar/examples/default";
import NavbarMenuDefault from "./navbar-menu/examples/default";
import StickyBannerDefault from "./sticky-banner/examples/default";
import FileDropDefault from "./file-drop/examples/default";
import StepperDefault from "./stepper/examples/default";
import VanishInputDefault from "./vanish-input/examples/default";
import AnimatedTestimonialsDefault from "./animated-testimonials/examples/default";
import LogoCloudDefault from "./logo-cloud/examples/default";
import TweetCardDefault from "./tweet-card/examples/default";
import ContainerScrollDefault from "./container-scroll/examples/default";
import ParallaxGridDefault from "./parallax-grid/examples/default";
import ScrollProgressDefault from "./scroll-progress/examples/default";
import ScrollVelocityDefault from "./scroll-velocity/examples/default";
import StickyScrollDefault from "./sticky-scroll/examples/default";
import TracingBeamDefault from "./tracing-beam/examples/default";
import AnimatedBeamDefault from "./animated-beam/examples/default";
import BlurFadeDefault from "./blur-fade/examples/default";
import BorderBeamDefault from "./border-beam/examples/default";
import BrowserMockupDefault from "./browser-mockup/examples/default";
import IphoneMockupDefault from "./iphone-mockup/examples/default";
import TerminalDefault from "./terminal/examples/default";

export const componentExamples: Record<
  string,
  { name: string; Component: ComponentType }[]
> = {
  "aurora-background": [{ name: "default", Component: AuroraBackgroundDefault }],
  "background-beams": [{ name: "default", Component: BackgroundBeamsDefault }],
  "flickering-grid": [{ name: "default", Component: FlickeringGridDefault }],
  "grid-pattern": [{ name: "default", Component: GridPatternDefault }],
  "lamp": [{ name: "default", Component: LampDefault }],
  "light-rays": [{ name: "default", Component: LightRaysDefault }],
  "meteors": [{ name: "default", Component: MeteorsDefault }],
  "particles": [{ name: "default", Component: ParticlesDefault }],
  "retro-grid": [{ name: "default", Component: RetroGridDefault }],
  "ripple": [{ name: "default", Component: RippleDefault }],
  "animated-gradient-text": [{ name: "default", Component: AnimatedGradientTextDefault }],
  "flip-words": [{ name: "default", Component: FlipWordsDefault }],
  "hyper-text": [{ name: "default", Component: HyperTextDefault }],
  "morphing-text": [{ name: "default", Component: MorphingTextDefault }],
  "number-ticker": [{ name: "default", Component: NumberTickerDefault }],
  "sparkles-text": [{ name: "default", Component: SparklesTextDefault }],
  "text-highlighter": [{ name: "default", Component: TextHighlighterDefault }],
  "text-reveal": [{ name: "default", Component: TextRevealDefault }],
  "text-shimmer": [{ name: "default", Component: TextShimmerDefault }],
  "typewriter": [{ name: "default", Component: TypewriterDefault }],
  "word-rotate": [{ name: "default", Component: WordRotateDefault }],
  "confetti": [{ name: "default", Component: ConfettiDefault }],
  "magnetic-button": [{ name: "default", Component: MagneticButtonDefault }],
  "moving-border": [{ name: "default", Component: MovingBorderDefault }],
  "rainbow-button": [{ name: "default", Component: RainbowButtonDefault }],
  "ripple-button": [{ name: "default", Component: RippleButtonDefault }],
  "shimmer-button": [{ name: "default", Component: ShimmerButtonDefault }],
  "theme-toggler": [{ name: "default", Component: ThemeTogglerDefault }],
  "animated-list": [{ name: "default", Component: AnimatedListDefault }],
  "animated-tooltip": [{ name: "default", Component: AnimatedTooltipDefault }],
  "avatar-circles": [{ name: "default", Component: AvatarCirclesDefault }],
  "bento-grid": [{ name: "default", Component: BentoGridDefault }],
  "card-stack": [{ name: "default", Component: CardStackDefault }],
  "compare-slider": [{ name: "default", Component: CompareSliderDefault }],
  "direction-aware-hover": [{ name: "default", Component: DirectionAwareHoverDefault }],
  "dock": [{ name: "default", Component: DockDefault }],
  "expandable-card": [{ name: "default", Component: ExpandableCardDefault }],
  "file-tree": [{ name: "default", Component: FileTreeDefault }],
  "glare-card": [{ name: "default", Component: GlareCardDefault }],
  "marquee": [{ name: "default", Component: MarqueeDefault }],
  "orbiting-circles": [{ name: "default", Component: OrbitingCirclesDefault }],
  "spotlight-card": [{ name: "default", Component: SpotlightCardDefault }],
  "tilt-card": [{ name: "default", Component: TiltCardDefault }],
  "floating-navbar": [{ name: "default", Component: FloatingNavbarDefault }],
  "navbar-menu": [{ name: "default", Component: NavbarMenuDefault }],
  "sticky-banner": [{ name: "default", Component: StickyBannerDefault }],
  "file-drop": [{ name: "default", Component: FileDropDefault }],
  "stepper": [{ name: "default", Component: StepperDefault }],
  "vanish-input": [{ name: "default", Component: VanishInputDefault }],
  "animated-testimonials": [{ name: "default", Component: AnimatedTestimonialsDefault }],
  "logo-cloud": [{ name: "default", Component: LogoCloudDefault }],
  "tweet-card": [{ name: "default", Component: TweetCardDefault }],
  "container-scroll": [{ name: "default", Component: ContainerScrollDefault }],
  "parallax-grid": [{ name: "default", Component: ParallaxGridDefault }],
  "scroll-progress": [{ name: "default", Component: ScrollProgressDefault }],
  "scroll-velocity": [{ name: "default", Component: ScrollVelocityDefault }],
  "sticky-scroll": [{ name: "default", Component: StickyScrollDefault }],
  "tracing-beam": [{ name: "default", Component: TracingBeamDefault }],
  "animated-beam": [{ name: "default", Component: AnimatedBeamDefault }],
  "blur-fade": [{ name: "default", Component: BlurFadeDefault }],
  "border-beam": [{ name: "default", Component: BorderBeamDefault }],
  "browser-mockup": [{ name: "default", Component: BrowserMockupDefault }],
  "iphone-mockup": [{ name: "default", Component: IphoneMockupDefault }],
  "terminal": [{ name: "default", Component: TerminalDefault }],
};
