// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

import { HeroAurora } from "@/components/blocks/hero-aurora";
import { HeroGlobe } from "@/components/blocks/hero-globe";
import { HeroScreenshot } from "@/components/blocks/hero-screenshot";
import { HeroSplitPhone } from "@/components/blocks/hero-split-phone";
import { HeroWaves } from "@/components/blocks/hero-waves";
import { HeroGridMinimal } from "@/components/blocks/hero-grid-minimal";
import { FeaturesBento } from "@/components/blocks/features-bento";
import { FeaturesIconGrid } from "@/components/blocks/features-icon-grid";
import { FeaturesTabs } from "@/components/blocks/features-tabs";
import { FeaturesSplitScreenshot } from "@/components/blocks/features-split-screenshot";
import { FeaturesSteps } from "@/components/blocks/features-steps";
import { PricingThreeTiers } from "@/components/blocks/pricing-three-tiers";
import { PricingSinglePlan } from "@/components/blocks/pricing-single-plan";
import { PricingComparison } from "@/components/blocks/pricing-comparison";
import { TestimonialsMarquee } from "@/components/blocks/testimonials-marquee";
import { TestimonialsFeatured } from "@/components/blocks/testimonials-featured";
import { TestimonialsGrid } from "@/components/blocks/testimonials-grid";
import { CtaVortex } from "@/components/blocks/cta-vortex";
import { CtaSplitImage } from "@/components/blocks/cta-split-image";
import { CtaNewsletter } from "@/components/blocks/cta-newsletter";
import { LogosMarquee } from "@/components/blocks/logos-marquee";
import { LogosGrid } from "@/components/blocks/logos-grid";
import { FaqAccordion } from "@/components/blocks/faq-accordion";
import { FaqTwoColumn } from "@/components/blocks/faq-two-column";
import { NavbarFloating } from "@/components/blocks/navbar-floating";
import { NavbarMega } from "@/components/blocks/navbar-mega";
import { FooterColumns } from "@/components/blocks/footer-columns";
import { FooterWordmark } from "@/components/blocks/footer-wordmark";
import { FooterNewsletter } from "@/components/blocks/footer-newsletter";
import { AuthLoginSplit } from "@/components/blocks/auth-login-split";
import { AuthSignupCard } from "@/components/blocks/auth-signup-card";

export const blockComponents: Record<string, ComponentType> = {
  "hero-aurora": HeroAurora,
  "hero-globe": HeroGlobe,
  "hero-screenshot": HeroScreenshot,
  "hero-split-phone": HeroSplitPhone,
  "hero-waves": HeroWaves,
  "hero-grid-minimal": HeroGridMinimal,
  "features-bento": FeaturesBento,
  "features-icon-grid": FeaturesIconGrid,
  "features-tabs": FeaturesTabs,
  "features-split-screenshot": FeaturesSplitScreenshot,
  "features-steps": FeaturesSteps,
  "pricing-three-tiers": PricingThreeTiers,
  "pricing-single-plan": PricingSinglePlan,
  "pricing-comparison": PricingComparison,
  "testimonials-marquee": TestimonialsMarquee,
  "testimonials-featured": TestimonialsFeatured,
  "testimonials-grid": TestimonialsGrid,
  "cta-vortex": CtaVortex,
  "cta-split-image": CtaSplitImage,
  "cta-newsletter": CtaNewsletter,
  "logos-marquee": LogosMarquee,
  "logos-grid": LogosGrid,
  "faq-accordion": FaqAccordion,
  "faq-two-column": FaqTwoColumn,
  "navbar-floating": NavbarFloating,
  "navbar-mega": NavbarMega,
  "footer-columns": FooterColumns,
  "footer-wordmark": FooterWordmark,
  "footer-newsletter": FooterNewsletter,
  "auth-login-split": AuthLoginSplit,
  "auth-signup-card": AuthSignupCard,
};
