// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

import { HeroAurora } from "@/components/blocks/hero-aurora";

export const blockComponents: Record<string, ComponentType> = {
  "hero-aurora": HeroAurora,
};
