// Assembles the docs catalogue from src/content/components/<slug>/:
//   meta.json            → src/lib/components-meta.json (read by the site and
//                           scripts/build-registry.mjs); every key, including
//                           the optional "since" release, passes through
//   examples/<name>.tsx  → src/content/components/index.ts (static imports)
// and extracts props tables from src/components/velora/<slug>.tsx
//                        → src/lib/component-props.json
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const require = createRequire(resolve(root, "package.json"));
const ts = require("typescript");

const contentDir = resolve(root, "src/content/components");
const categories = JSON.parse(
  readFileSync(resolve(root, "src/content/categories.json"), "utf8")
);
const categoryCopy = JSON.parse(
  readFileSync(resolve(root, "src/content/component-category-copy.json"), "utf8")
);
for (const c of categories) {
  if (!categoryCopy[c]) throw new Error(`component-category-copy.json: no copy for "${c}"`);
}

// ---------------------------------------------------------------------------
// Catalogue
// ---------------------------------------------------------------------------

const REQUIRED = ["title", "description", "category", "dependencies", "examples"];

const docs = readdirSync(contentDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map(({ name: slug }) => {
    const meta = JSON.parse(
      readFileSync(resolve(contentDir, slug, "meta.json"), "utf8")
    );
    for (const key of REQUIRED) {
      if (!(key in meta)) throw new Error(`${slug}/meta.json: missing "${key}"`);
    }
    if (!categories.includes(meta.category)) {
      throw new Error(`${slug}/meta.json: unknown category "${meta.category}"`);
    }
    if (!existsSync(resolve(root, "src/components/velora", `${slug}.tsx`))) {
      throw new Error(`${slug}: no src/components/velora/${slug}.tsx`);
    }
    // Optional release the component first shipped in (drives "New" badges).
    if ("since" in meta && !/^\d+\.\d+\.\d+$/.test(meta.since)) {
      throw new Error(`${slug}/meta.json: "since" must be a version like "0.7.0"`);
    }
    if (meta.examples[0]?.name !== "default") {
      throw new Error(`${slug}/meta.json: first example must be "default"`);
    }
    for (const ex of meta.examples) {
      if (!existsSync(resolve(contentDir, slug, "examples", `${ex.name}.tsx`))) {
        throw new Error(`${slug}: missing examples/${ex.name}.tsx`);
      }
    }
    return { slug, ...meta };
  })
  .sort(
    (a, b) =>
      categories.indexOf(a.category) - categories.indexOf(b.category) ||
      a.title.localeCompare(b.title)
  );

writeFileSync(
  resolve(root, "src/lib/components-meta.json"),
  JSON.stringify(
    docs.map(({ examples, ...rest }) => ({
      ...rest,
      examples: examples.map(({ name, title, description }) => ({
        name,
        title,
        ...(description ? { description } : {}),
      })),
    })),
    null,
    2
  ) + "\n"
);

// ---------------------------------------------------------------------------
// Example index — static imports so every demo is prerendered.
// ---------------------------------------------------------------------------

// Slugs like "3d-pin" start with a digit, so prefix to keep a valid identifier.
const ident = (slug, name) =>
  `example-${slug}-${name}`.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

const importLines = [];
const entries = [];
for (const doc of docs) {
  const items = doc.examples.map((ex) => {
    const id = ident(doc.slug, ex.name);
    importLines.push(`import ${id} from "./${doc.slug}/examples/${ex.name}";`);
    return `{ name: ${JSON.stringify(ex.name)}, Component: ${id} }`;
  });
  entries.push(`  ${JSON.stringify(doc.slug)}: [${items.join(", ")}],`);
}

writeFileSync(
  resolve(contentDir, "index.ts"),
  `// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

${importLines.join("\n")}

export const componentExamples: Record<
  string,
  { name: string; Component: ComponentType }[]
> = {
${entries.join("\n")}
};
`
);

// ---------------------------------------------------------------------------
// Props — parsed from the component source (syntax only, no type checker).
// ---------------------------------------------------------------------------

const jsDocText = (node) => {
  const doc = ts.getJSDocCommentsAndTags(node).find(ts.isJSDoc);
  const text = doc?.comment;
  if (!text) return undefined;
  return (typeof text === "string" ? text : text.map((t) => t.text).join(""))
    .replace(/\s+/g, " ")
    .trim();
};

const jsDocDefault = (node) =>
  ts
    .getJSDocTags(node)
    .find((t) => t.tagName.text === "default")
    ?.comment?.toString()
    .trim();

function membersOf(typeNode, locals) {
  // → { props: TypeElement[], extends: string[] }
  if (!typeNode) return { props: [], extends: [] };
  if (ts.isTypeLiteralNode(typeNode)) return { props: [...typeNode.members], extends: [] };
  if (ts.isIntersectionTypeNode(typeNode)) {
    return typeNode.types.reduce(
      (acc, t) => {
        const m = membersOf(t, locals);
        return { props: [...acc.props, ...m.props], extends: [...acc.extends, ...m.extends] };
      },
      { props: [], extends: [] }
    );
  }
  if (ts.isTypeReferenceNode(typeNode)) {
    const decl = locals.get(typeNode.typeName.getText());
    if (!decl) return { props: [], extends: [typeNode.getText()] };
    if (ts.isInterfaceDeclaration(decl)) {
      const heritage = (decl.heritageClauses ?? []).flatMap((h) =>
        h.types.map((t) => t.getText())
      );
      return { props: [...decl.members], extends: heritage };
    }
    if (ts.isTypeAliasDeclaration(decl)) return membersOf(decl.type, locals);
  }
  return { props: [], extends: [typeNode.getText()] };
}

function extractProps(slug) {
  const file = resolve(root, "src/components/velora", `${slug}.tsx`);
  const sf = ts.createSourceFile(
    file,
    readFileSync(file, "utf8"),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX
  );

  const locals = new Map();
  const exported = [];
  for (const st of sf.statements) {
    if (ts.isInterfaceDeclaration(st) || ts.isTypeAliasDeclaration(st)) {
      locals.set(st.name.text, st);
    }
    const isExport = st.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
    if (!isExport) continue;
    if (ts.isFunctionDeclaration(st) && st.name && /^[A-Z]/.test(st.name.text)) {
      exported.push({ name: st.name.text, fn: st });
    } else if (ts.isVariableStatement(st)) {
      for (const d of st.declarationList.declarations) {
        const init = d.initializer;
        if (
          /^[A-Z]/.test(d.name.getText()) &&
          init &&
          (ts.isArrowFunction(init) || ts.isFunctionExpression(init))
        ) {
          exported.push({ name: d.name.getText(), fn: init });
        }
      }
    }
  }

  const referenced = new Set();
  const components = exported.map(({ name, fn }) => {
    const param = fn.parameters[0];
    const defaults = new Map();
    let forwardsRest = false;
    if (param && ts.isObjectBindingPattern(param.name)) {
      forwardsRest = param.name.elements.some((el) => el.dotDotDotToken);
      for (const el of param.name.elements) {
        if (el.initializer) {
          const key = (el.propertyName ?? el.name).getText();
          defaults.set(key, el.initializer.getText());
        }
      }
    }
    const { props, extends: ext } = membersOf(param?.type, locals);
    const description = jsDocText(fn.parent && ts.isVariableDeclaration(fn.parent) ? fn.parent.parent.parent : fn);

    return {
      name,
      ...(description ? { description } : {}),
      extends: ext,
      forwardsRest,
      props: props
        .filter((m) => ts.isPropertySignature(m) || ts.isMethodSignature(m))
        .map((m) => {
          const propName = m.name.getText();
          const type = m.type ? m.type.getText().replace(/\s+/g, " ") : "unknown";
          for (const [local] of locals) {
            if (new RegExp(`\\b${local}\\b`).test(type)) referenced.add(local);
          }
          const def = defaults.get(propName) ?? jsDocDefault(m);
          const description = jsDocText(m);
          return {
            name: propName,
            type,
            required: !m.questionToken,
            ...(def ? { default: def } : {}),
            ...(description ? { description } : {}),
          };
        }),
    };
  });

  // Item shapes referenced by props (e.g. Testimonial, FileNode).
  const types = [...referenced]
    .map((n) => locals.get(n))
    .filter((d) => ts.isInterfaceDeclaration(d) || ts.isTypeAliasDeclaration(d))
    .filter((d) => !/Props$/.test(d.name.text))
    .map((d) => ({ name: d.name.text, source: d.getText().replace(/^export /, "") }));

  return { components: components.filter((c) => c.props.length || c.extends.length), types };
}

const props = Object.fromEntries(docs.map((d) => [d.slug, extractProps(d.slug)]));

// An interface that extends native attributes but a component that never
// spreads them silently drops aria-*, id, onClick… — fail loudly instead.
const dropped = Object.entries(props).flatMap(([slug, p]) =>
  p.components
    .filter((c) => c.extends.length && !c.forwardsRest)
    .map((c) => `${slug}: ${c.name} extends ${c.extends.join(", ")} but never spreads ...props`)
);
if (dropped.length) {
  console.warn(`docs: ${dropped.length} component(s) drop native props:\n  ${dropped.join("\n  ")}`);
}
writeFileSync(
  resolve(root, "src/lib/component-props.json"),
  JSON.stringify(props, null, 2) + "\n"
);

const propCount = Object.values(props).reduce(
  (n, p) => n + p.components.reduce((m, c) => m + c.props.length, 0),
  0
);
console.log(
  `docs: ${docs.length} components, ${importLines.length} examples, ${propCount} props`
);

// ---------------------------------------------------------------------------
// Blocks — full sections in src/components/blocks/<slug>.tsx, documented by
// src/content/blocks/<slug>/meta.json. Dependencies are read from the
// imports so the registry can't drift from the code.
//   → src/lib/blocks-meta.json, src/content/blocks/index.ts
// ---------------------------------------------------------------------------

const blockCategories = JSON.parse(
  readFileSync(resolve(root, "src/content/block-categories.json"), "utf8")
);
const blocksDir = resolve(root, "src/content/blocks");
const componentSlugs = new Set(docs.map((d) => d.slug));

const blocks = (existsSync(blocksDir) ? readdirSync(blocksDir, { withFileTypes: true }) : [])
  .filter((d) => d.isDirectory())
  .map(({ name: slug }) => {
    const meta = JSON.parse(readFileSync(resolve(blocksDir, slug, "meta.json"), "utf8"));
    for (const key of ["title", "description", "category"]) {
      if (!(key in meta)) throw new Error(`blocks/${slug}/meta.json: missing "${key}"`);
    }
    if (!blockCategories.some((c) => c.slug === meta.category)) {
      throw new Error(`blocks/${slug}/meta.json: unknown category "${meta.category}"`);
    }
    if (componentSlugs.has(slug)) {
      throw new Error(`blocks/${slug}: slug collides with a component of the same name`);
    }
    const file = resolve(root, "src/components/blocks", `${slug}.tsx`);
    if (!existsSync(file)) throw new Error(`blocks/${slug}: no src/components/blocks/${slug}.tsx`);
    const source = readFileSync(file, "utf8");

    const specifiers = [...source.matchAll(/^import\s+(?!type\b)[^;]*?from\s+"([^"]+)"/gms)].map((m) => m[1]);
    const components = [...new Set(specifiers.filter((s) => s.startsWith("@/components/velora/")).map((s) => s.split("/").pop()))];
    const ui = [...new Set(specifiers.filter((s) => s.startsWith("@/components/ui/")).map((s) => s.split("/").pop()))];
    const dependencies = [...new Set(specifiers.filter((s) => !s.startsWith("@/") && !s.startsWith(".") && s !== "react" && s !== "react-dom").map((s) => (s.startsWith("@") ? s.split("/").slice(0, 2).join("/") : s.split("/")[0])))];
    for (const c of components) {
      if (!componentSlugs.has(c)) throw new Error(`blocks/${slug}: imports unknown component "${c}"`);
    }
    const unexpected = specifiers.filter(
      (s) => s.startsWith("@/") && !/^@\/components\/(velora|ui)\//.test(s) && s !== "@/lib/utils"
    );
    if (unexpected.length) {
      throw new Error(`blocks/${slug}: imports site-only modules (${unexpected.join(", ")}) — blocks must be installable`);
    }
    const exportName = source.match(/^export function ([A-Z]\w*)/m)?.[1];
    if (!exportName) throw new Error(`blocks/${slug}: needs a named "export function Name()"`);

    return { slug, ...meta, exportName, components, ui, dependencies };
  })
  .sort(
    (a, b) =>
      blockCategories.findIndex((c) => c.slug === a.category) -
        blockCategories.findIndex((c) => c.slug === b.category) ||
      (a.order ?? 99) - (b.order ?? 99) ||
      a.title.localeCompare(b.title)
  );

writeFileSync(
  resolve(root, "src/lib/blocks-meta.json"),
  JSON.stringify(blocks, null, 2) + "\n"
);

writeFileSync(
  resolve(blocksDir, "..", "blocks-index.ts"),
  `// Generated by scripts/build-docs.mjs — do not edit.
import type { ComponentType } from "react";

${blocks.map((b) => `import { ${b.exportName} } from "@/components/blocks/${b.slug}";`).join("\n")}

export const blockComponents: Record<string, ComponentType> = {
${blocks.map((b) => `  ${JSON.stringify(b.slug)}: ${b.exportName},`).join("\n")}
};
`
);

console.log(`docs: ${blocks.length} blocks in ${new Set(blocks.map((b) => b.category)).size} categories`);
